name: ont_fragment_dashboard
channels:
  - bioconda
  - conda-forge
dependencies:
  - python=3.10
  - samtools
  - minimap2
  - pip
  - pip:
      - pandas
      - pysam
      - plotly
      - ipywidgets
      - notebook
      - jupyterlab
      - voila
      - nbformat